name: Premerge Workflow
on: [workflow_dispatch, push]
run-name: Check whether the standard checks are running
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Run tests
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: [install, test]
    steps:
      - name: Build code
        run: npm run build
